LostItemproject/LostItemproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('top.urls')),
    path('lostitem/', include('lostitem.urls')),
    path('founditem/', include('founditem.urls')),
    path("mypage/", include("mypage.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LostItemproject/founditem/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'founditem'

urlpatterns = [
    path('', views.index, name='index'),
    path('tofounditemregister/', views.tofounditemregister, name='tofounditemregister'),
    path('registeritem/', views.register_item, name='register_item'),
    path('image/<int:id>/', views.get_image, name='get_image'),
    path('validate_qr_code', views.validate_qr_code, name='validate_qr_code'),
    path('generate_qr_code/', views.generate_qr_code, name='generate_qr_code'),
]

LostItemproject/lostitem/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'lostitem'  # 名前空間の定義

urlpatterns = [
    path('', views.index, name='index'),
    path('restartPassword/', auth_views.PasswordResetView.as_view(),
             name='resetPassword'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('tolostitemregister/', views.tolostitemregister, name='tolostitemregister'),
    path('registeritem/', views.register_item, name='register_item'),
]

LostItemproject/mypage/urls.py
from django.urls import path
from mypage import views
from django.contrib import admin # 一時的

app_name = "mypage"

urlpatterns = [
    # path("admin/", admin.site.urls), # 管理者がマイページに行くとadmin管理画面に行く（一時的）
    path("student/", views.student_mypage, name="student_mypage"), # 学生マイページ表示
    path("administrator/", views.admin_mypage, name="admin_mypage"),
    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),
]

LostItemproject/top/urls.py
from django.urls import path
from . import views

app_name = 'top'  # 名前空間の定義

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='home'),
]

LostItemproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/top.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'imgs/favicon_io/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/lost_item_register.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/main.css' %}"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>落とし物管理</title>
</head>
<body>
    <main>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
            <div class="container">
              <a class="navbar-brand" href="{% url 'top:home' %}">
                <img src = "{% static 'imgs/illustrations/1. FINAL logo png.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top img-fluid">
                落とし物管理アプリ
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarXL" aria-controls="navbarXL" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button> -->
              <div class="collapse navbar-collapse justify-content-end" id="navbarXL">
                <ul class="navbar-nav ml-auto">
                  {% if user.is_superuser %}<!--管理者アカウントかどうか-->
                    <li class="nav-item">
                      <span class="navbar-text">Welcome, {{ user.username }}!</span>
                    </li>
                    <!-- 一時的な処理 -->
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'mypage:admin_mypage' %}">マイページ</a>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'lostitem:tolostitemregister' %}">遺失物登録</a>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'founditem:tofounditemregister' %}">拾得物登録</a>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'lostitem:logout' %}">ログアウト</a>
                    </li>
                  {% elif user.is_authenticated %}<!--そうでないアカウントの場合-->
                    <li class="nav-item">
                        <span class="navbar-text">Welcome, {{ user.username }}!</span>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'mypage:student_mypage' %}">マイページ</a>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'lostitem:tolostitemregister' %}">遺失物登録</a>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'lostitem:logout' %}">ログアウト</a>
                  </li>
                  {% else %}<!--ログインしていない場合-->
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'lostitem:login' %}">ログイン</a>
                    </li>
                    <li class="nav-item mx-3">
                      <a class="nav-link" href="{% url 'founditem:tofounditemregister' %}">拾得物登録</a>
                    </li>
                  {% endif %}
        
                </ul>
                <!--
                 <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-end">
                  <li class="nav-item">
                    <a class="nav-link" href="#">ログイン</a>
                  </li>
                </ul>
                -->
              </div>
            </div>
        </nav>
        <div style="margin-top: 55px;">
            {% block content %}
            <p>This is the default content.</p>
            {% endblock %}
        </div>
    </main>
</body>
<footer>
    <div class="container py-3 ">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">ここはフッターです</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
      </div>
</footer>
</html>